# Generated by Django 3.1.6 on 2021-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210224_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='uu_id',
            field=models.UUIDField(),
        ),
    ]
