# Generated by Django 3.1.6 on 2021-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210224_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
