# Generated by Django 3.1.6 on 2021-02-25 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210225_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
