# Generated by Django 3.1.6 on 2021-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210225_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='decimal',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
