# Generated by Django 3.1.6 on 2021-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210225_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, null=True, to='app.Privilege'),
        ),
    ]
