# Generated by Django 3.1.6 on 2021-02-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210225_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='file_path',
        ),
    ]
