# Generated by Django 3.1.6 on 2021-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_example_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='positive_big_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='positive_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='positive_small_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='small_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
