# Generated by Django 3.1.6 on 2021-03-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210301_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
