# Generated by Django 3.1.6 on 2021-03-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210301_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='boolean',
            field=models.BooleanField(default=True),
        ),
    ]
