# Generated by Django 3.1.6 on 2021-03-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210304_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='example',
            name='last_name',
            field=models.CharField(db_index=True, default='', max_length=56, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='example',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=56, verbose_name='Отчество'),
        ),
    ]
