# Generated by Django 3.1.6 on 2021-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210304_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН'),
        ),
    ]
