# Generated by Django 3.1.6 on 2021-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_example_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='payment_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Сумма платежей за все время'),
        ),
    ]
