# Generated by Django 3.1.6 on 2021-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_example_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Название'),
        ),
    ]
