# Generated by Django 3.1.6 on 2021-03-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210304_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='title',
        ),
    ]
